import 'package:pick_champ/feature/quiz/model/response/quiz.dart';

class MockQuizList {
  final list = [
    Quiz(
      id: '1',
      title: 'Gelmiş Geçmiş En İyi Futbolcu',
      description:
          'Let the world decide who the greatest football player of all time is.',
      userId: 'user_001',
      categoryId: 4,
      photoSnapshot: 'profile.png',
      displayNameSnapshot: 'Pick Champ User',
      comments: ['çok kaliteli', 'çok güzel', 'inanılmaz'],
      reactionCount: 13,
      history: [
        '1',
        '2',
        '1',
        '2',
        '1',
        '2',
        '1',
        '2',
        '2',
        '1',
        '2',
        '1',
        '2',
        '2',
        '1',
        '2',
        '1',
        '2',
        '1',
        '2',
        '1',
        '2',
        '1',
        '2',
        '1',
        '2',
        '2',
        '1',
        '2',
        '1',
        '2',
        '2',
        '1',
        '2',
        '1',
        '2',
      ],
      coverImage:
          'https://cdn.britannica.com/35/238335-050-2CB2EB8A/Lionel-Messi-Argentina-Netherlands-World-Cup-Qatar-2022.jpg',
      selections: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
      ],

      isEditorSelected: true,
    ),
    Quiz(
      id: '2',
      title: 'Most Clever People In History',
      description:
          'A mind-bending showdown to find out who truly changed the world with their genius.',
      reactionCount: 121,
      categoryId: 8,
      photoSnapshot: 'profile.png',
      displayNameSnapshot: 'Pick Champ User',
      comments: ['çok kaliteli', 'çok güzel', 'inanılmaz'],
      userId: 'user_002',
      history: ['1', '2', '1', '2', '1', '2', '1', '2'],
      coverImage:
          'https://c02.purpledshub.com/uploads/sites/41/2023/05/albert-einstein-3814ca6.jpg?webp=1&w=1200',
      selections: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
      ],

      isAnonymous: true,
    ),
    Quiz(
      id: '3',
      title: 'Most Popular Streamer',
      description:
          'Vote for the content creator who rules the digital world!',
      reactionCount: 25,
      categoryId: 9,
      history: ['1', '2', '1', '2', '1', '2', '1', '2'],
      photoSnapshot: 'profile.png',
      displayNameSnapshot: 'Pick Champ User',
      comments: ['çok kaliteli', 'çok güzel', 'inanılmaz'],
      userId: 'user_003',
      coverImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/IShowSpeed_at_Chinatown_%28Portrait%29_04.jpg/500px-IShowSpeed_at_Chinatown_%28Portrait%29_04.jpg',
      tags: ['kültür', 'genel', 'test'],
      selections: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
      ],
    ),
  ];
}
